services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  FRUIT\StaticExport\:
    resource: '../Classes/*'

  FRUIT\StaticExport\EventListener\ExportAssetsEventListener:
    tags:
      - name: event.listener
        event: FRUIT\StaticExport\Event\CreateExportEvent

  FRUIT\StaticExport\EventListener\ExportPagesEventListener:
    tags:
      - name: event.listener
        event: FRUIT\StaticExport\Event\CreateExportEvent

  FRUIT\StaticExport\EventListener\MainContentOnlyProcessContentEventListener:
    tags:
      - name: event.listener
        event: FRUIT\StaticExport\Event\ProcessContentEvent
