services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  FRUIT\StaticExport\:
    resource: '../Classes/*'

  FRUIT\StaticExport\EventListener\AssetsCreateExportEventListener:
    tags:
      - name: event.listener
        event: FRUIT\StaticExport\Event\CreateExportEvent

  FRUIT\StaticExport\EventListener\PagesCreateExportEventListener:
    tags:
      - name: event.listener
        event: FRUIT\StaticExport\Event\CreateExportEvent

  FRUIT\StaticExport\EventListener\MainContentOnlyProcessContentEventListener:
    tags:
      - name: event.listener
        event: FRUIT\StaticExport\Event\ProcessContentEvent

  FRUIT\StaticExport\Command\ExportAndPublishCommand:
    tags:
      - name: 'console.command'
        command: 'staticexport:export-and-publish'

  FRUIT\StaticExport\Command\CleanupCommand:
    tags:
      - name: 'console.command'
        command: 'staticexport:cleanup'